[package]
name = "laut-compat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "io-util",
    "macros",
    "sync",
    "rt",
]}
tracing.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
nix-compat = { path = "../nix-compat" }
snix-castore = { path = "../castore" }
snix-store = { path = "../store" }